on: workflow_dispatch
name: Setup Spring Cloud App
jobs:
  setup-springcloud-app:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@main

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Setup Spring Cloud Service
      uses: Azure/cli@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az config set extension.use_dynamic_install=yes_without_prompt
          az spring-cloud app create --name hello-springcloud --resource-group ${{ secrets.RESOURCE_GROUP_NAME }} --service ${{ secrets.SPRINGCLOUD_SERVICE }}
